global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'url-shortener'

scrape_configs:
  - job_name: 'url-shortener-app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s

